"""Bibliothèque de tâches type par entreprise, utilisée par le générateur de
planning (schedule_generator.py) pour produire une semaine réaliste.

Chaque entrée : (titre, nom de catégorie ou None, durée estimée en minutes).
Une tâche appartient toujours à une seule entreprise — ces listes ne sont
jamais mélangées entre entreprises.
"""

TASK_TEMPLATES: dict[str, list[tuple[str, str | None, int]]] = {
    "mobilier-malin": [
        ("Optimiser fiche produit", "Fiches produits", 30),
        ("Créer nouvelle fiche produit", "Fiches produits", 40),
        ("Optimiser page catégorie", "Catégories", 30),
        ("Optimiser collection", "Collections", 30),
        ("Ajouter maillage interne", "Maillage interne", 25),
        ("Créer liens internes", "Maillage interne", 20),
        ("Vérifier H1", "SEO", 15),
        ("Vérifier Title", "SEO", 15),
        ("Vérifier meta description", "Meta descriptions", 20),
        ("Optimiser images produit", "Images", 25),
        ("Renommer fichiers images", "Images", 15),
        ("Vérifier attributs alt images", "Images", 15),
        ("Rédiger article de blog", "Blog", 60),
        ("Publier article de blog", "Blog", 30),
        ("Corriger erreurs Search Console", "Search Console", 30),
        ("Demande d'indexation Search Console", "Search Console", 15),
        ("Vérifier Google Merchant Center", "Google Merchant Center", 20),
        ("Corriger produits refusés Merchant Center", "Google Merchant Center", 30),
        ("Vérifier Google Shopping", "Google Shopping", 20),
        ("Vérifier Analytics", "Analytics", 20),
        ("Créer publication Pinterest", "Pinterest", 20),
        ("Programmer publications Pinterest", "Pinterest", 25),
        ("Créer publication Facebook", "Facebook", 20),
        ("Créer publication Instagram", "Instagram", 20),
        ("Créer Reel Instagram", "Instagram", 35),
        ("Optimiser page marque", "SEO", 30),
        ("Recherche de mots-clés", "SEO", 45),
        ("Analyse concurrentielle", "SEO", 45),
        ("Vérifier erreurs 404", "SEO", 20),
        ("Vérifier backlinks", "Backlinks", 30),
        ("Recherche de nouveaux backlinks", "Backlinks", 45),
    ],
    "trust-industrie": [
        ("Audit SEMrush complet", "SEMrush", 90),
        ("Analyser rapport SEMrush", "SEMrush", 45),
        ("Corriger balises H1", "H1", 20),
        ("Corriger balises H2", "H2", 20),
        ("Corriger balises Title", "Titles", 20),
        ("Corriger meta descriptions", "Meta descriptions", 25),
        ("Nettoyer URLs non conformes", "Nettoyage SEO", 30),
        ("Corriger balises canonical", "Nettoyage SEO", 25),
        ("Corriger pages 404", "404", 30),
        ("Corriger redirections", "Redirections", 30),
        ("Vérifier Search Console", "Search Console", 20),
        ("Vérifier Analytics", "Analytics", 20),
        ("Optimiser catégories produits", "Catégories", 30),
        ("Optimiser fiches produits", "Produits", 30),
        ("Optimiser contenus existants", "Blog", 35),
        ("Ajouter maillage interne", "Maillage interne", 25),
        ("Rédiger article SEO", "Blog", 60),
        ("Recherche de mots-clés", "SEO", 45),
        ("Analyse concurrentielle", "SEO", 45),
        ("Vérifier backlinks existants", "Backlinks", 30),
        ("Trouver nouveaux backlinks", "Backlinks", 45),
        ("Vérifier performances globales", "Analytics", 30),
        ("Auditer structure du site", "Audit SEO", 60),
        ("Auditer maillage interne", "Audit SEO", 45),
    ],
    "easymove-wear": [
        ("Créer produit Temu", "Temu", 40),
        ("Optimiser produit Temu", "Temu", 25),
        ("Vérifier statut produits Temu", "Temu", 15),
        ("Créer fiche TikTok Shop", "TikTok Shop", 40),
        ("Optimiser fiche TikTok Shop", "TikTok Shop", 25),
        ("Vérifier produits TikTok Shop", "TikTok Shop", 15),
        ("Rédiger SEO fiche produit", "SEO", 30),
        ("Créer fiche produit", "Fiches produits", 35),
        ("Optimiser fiche produit", "Fiches produits", 25),
        ("Créer publication Pinterest", "Pinterest", 20),
        ("Créer publication Facebook", "Facebook", 20),
        ("Créer publication Instagram", "Instagram", 20),
        ("Créer vidéo TikTok", "TikTok", 35),
        ("Créer Reel produit", "Instagram", 35),
        ("Optimiser images produit", "Images", 25),
        ("Créer contenu promotionnel", "Contenu", 30),
        ("Vérifier Search Console", "Search Console", 20),
        ("Vérifier Analytics", "Analytics", 20),
        ("Recherche de mots-clés", "SEO", 40),
        ("Analyse concurrentielle", "SEO", 40),
    ],
    "dreams-fly": [
        ("Rédiger article de blog", "Blog", 60),
        ("Optimiser article existant", "Blog", 30),
        ("Optimiser page SEO", "SEO", 30),
        ("Créer publication Pinterest", "Pinterest", 20),
        ("Créer publication Facebook", "Facebook", 20),
        ("Créer publication Instagram", "Instagram", 20),
        ("Créer contenu inspirant", "Contenu", 30),
        ("Vérifier Search Console", "Search Console", 20),
        ("Vérifier Analytics", "Analytics", 20),
        ("Recherche de mots-clés", "SEO", 40),
        ("Analyse concurrentielle", "SEO", 40),
    ],
}

# Tâches récurrentes générées une fois par entreprise, un jour fixe de la semaine.
# (titre, nom de catégorie ou None, durée en minutes)
MONDAY_RECURRING: list[tuple[str, str | None, int]] = [
    ("Vérifier Search Console", "Search Console", 15),
    ("Vérifier Analytics", "Analytics", 15),
    ("Vérifier KPI de la semaine", None, 20),
    ("Vérifier e-mails", None, 15),
]

FRIDAY_RECURRING: list[tuple[str, str | None, int]] = [
    ("Faire le rapport de la semaine", None, 45),
    ("Mettre à jour les KPI", None, 30),
    ("Planifier la semaine suivante", None, 30),
    ("Vérifier les tâches reportées", None, 20),
]
